/* Generated by re2c @PACKAGE_VERSION@ on Mon Mar 09 14:45:11 2009 */
// iniâêÕÉÇÉWÉÖÅ[Éã(re2c)
#pragma once

class RequestScanner{

public:

enum SCAN_CONDITION {
	SCAN_CONDITION_HEAD,
	SCAN_CONDITION_START,
	SCAN_CONDITION_PROTOCOL,
	SCAN_CONDITION_SPLIT,
	SCAN_CONDITION_VALUE,
	SCAN_CONDITION_SECTION,
	SCAN_CONDITION_SKIP,
};


	enum SCAN_TOKEN {
		TOKEN_EOT = 0,
		TOKEN_LEXER_ERROR,
		TOKEN_LEXER_SKIP,
		TOKEN_PROTOCOL_NAME,
		TOKEN_PROTOCOL_METHOD,
		TOKEN_COMMENT_LINE,
		TOKEN_ITEM_KEYWORD,
		TOKEN_ITEM_SPLIT,
		TOKEN_ITEM_VALUE,
		TOKEN_ITEM_VALUE_QUOT,
		TOKEN_SECTION_HEADER,
		TOKEN_SECTION_NAME,
	};
	class Token {
	private:
		const SCAN_TOKEN mToken;
		LPCTSTR mStart;
		LPCTSTR mEnd;
	public:
		Token(SCAN_TOKEN token, LPCTSTR start, LPCTSTR end)
			:mToken(token)
			,mStart(start)
			,mEnd(end)
		{}
		SCAN_TOKEN GetToken() const { return mToken; }
		int GetTextLength() const { return (int)((mEnd-mStart) / sizeof(TCHAR) );  }
		CString GetText() const { return CString(mStart, GetTextLength()); }
	};

private:
	CString mText;
	LPTSTR YYMARKER;
	SCAN_CONDITION mCondition;
	typedef Token TT;

public:
	RequestScanner(LPCTSTR text)
	{
		mText = text;
		YYMARKER = (LPTSTR)((LPCTSTR)mText);
		SetCondition(SCAN_CONDITION_START);
	}

	SCAN_CONDITION GetCondition() const { return mCondition; }
	void SetCondition(SCAN_CONDITION cond) { mCondition = cond; }

	Token Scan()
	{
		LPTSTR st  = YYMARKER;
		LPTSTR pos = YYMARKER;
		if(*st == 0) return TT(TOKEN_EOT,st,pos);

// ============================================================
// re2c define
// ============================================================


// ============================================================
// word class: Unicode category
// ============================================================


// ============================================================
// word class:
// ============================================================


// ============================================================
// token:
// ============================================================


// ============================================================
// scaner
// (SAMPLE)
// 1: SHIORI/3.0 GET	: protocol any
// 2: charset: UTF-8	: keyword: value
// 4: [section]			: [keyword]
// 5: #xxxxxx			: # any
// 6: (space)			: spaces
// ============================================================

			{
				TCHAR yych;
				unsigned int yyaccept = 0;
				if (GetCondition() < 3) {
					if (GetCondition() < 1) {
						goto yyc_HEAD;
					} else {
						if (GetCondition() < 2) {
							goto yyc_START;
						} else {
							goto yyc_PROTOCOL;
						}
					}
				} else {
					if (GetCondition() < 5) {
						if (GetCondition() < 4) {
							goto yyc_SPLIT;
						} else {
							goto yyc_VALUE;
						}
					} else {
						if (GetCondition() < 6) {
							goto yyc_SECTION;
						} else {
							goto yyc_SKIP;
						}
					}
				}
// *********************************** [HEAD]
yyc_HEAD:

				yych = *pos;
				if (yych <= 0x0085) {
					if (yych <= '"') {
						if (yych <= '\f') {
							if (yych <= 0x0008) goto yy12;
							if (yych <= '\t') goto yy4;
							if (yych <= '\n') goto yy5;
							goto yy12;
						} else {
							if (yych <= '\r') goto yy7;
							if (yych == ' ') goto yy4;
							goto yy12;
						}
					} else {
						if (yych <= '[') {
							if (yych <= '#') goto yy2;
							if (yych <= '-') goto yy12;
							if (yych <= 'Z') goto yy10;
							goto yy8;
						} else {
							if (yych <= '`') {
								if (yych <= '_') goto yy10;
								goto yy12;
							} else {
								if (yych <= 'z') goto yy10;
								if (yych <= 0x0084) goto yy12;
								goto yy4;
							}
						}
					}
				} else {
					if (yych <= 0x200A) {
						if (yych <= 0x1680) {
							if (yych == 0x00A0) goto yy4;
							if (yych <= 0x167F) goto yy12;
							goto yy4;
						} else {
							if (yych == 0x180E) goto yy4;
							if (yych <= 0x1FFF) goto yy12;
							goto yy4;
						}
					} else {
						if (yych <= 0x202F) {
							if (yych <= 0x2027) goto yy12;
							if (yych <= 0x2029) goto yy4;
							if (yych <= 0x202E) goto yy12;
							goto yy4;
						} else {
							if (yych <= 0x205F) {
								if (yych <= 0x205E) goto yy12;
								goto yy4;
							} else {
								if (yych == 0x3000) goto yy4;
								goto yy12;
							}
						}
					}
				}
yy2:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				goto yy20;
yy3:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy4:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				if (yych <= 0x1680) {
					if (yych <= ' ') {
						if (yych <= '\f') {
							if (yych <= 0x0008) goto yy3;
							if (yych <= '\n') goto yy17;
							goto yy3;
						} else {
							if (yych <= '\r') goto yy17;
							if (yych <= 0x001F) goto yy3;
							goto yy17;
						}
					} else {
						if (yych <= 0x009F) {
							if (yych == 0x0085) goto yy17;
							goto yy3;
						} else {
							if (yych <= 0x00A0) goto yy17;
							if (yych <= 0x167F) goto yy3;
							goto yy17;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy17;
							goto yy3;
						} else {
							if (yych <= 0x200A) goto yy17;
							if (yych <= 0x2027) goto yy3;
							goto yy17;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy17;
							goto yy3;
						} else {
							if (yych <= 0x205F) goto yy17;
							if (yych == 0x3000) goto yy17;
							goto yy3;
						}
					}
				}
yy5:
				++pos;
yy6:
				{ return TT(TOKEN_COMMENT_LINE,st,pos); }
yy7:
				yych = *++pos;
				if (yych == '\n') goto yy5;
				goto yy6;
yy8:
				++pos;
				if ((yych = *pos) <= '-') goto yy9;
				if (yych == '`') goto yy9;
				if (yych <= 'z') goto yy13;
yy9:
				SetCondition(SCAN_CONDITION_SECTION);
				{ return TT(TOKEN_SECTION_HEADER,st,pos); }
yy10:
				++pos;
				yych = *pos;
				goto yy14;
yy11:
				SetCondition(SCAN_CONDITION_SPLIT);
				{ return TT(TOKEN_ITEM_KEYWORD,st,pos); }
yy12:
				yych = *++pos;
				goto yy3;
yy13:
				++pos;
				yych = *pos;
yy14:
				if (yych <= '-') goto yy11;
				if (yych == '`') goto yy11;
				if (yych <= 'z') goto yy13;
				goto yy11;
yy15:
				yych = *++pos;
				if (yych == '\n') goto yy5;
				goto yy6;
yy16:
				++pos;
				yych = *pos;
yy17:
				if (yych <= 0x1680) {
					if (yych <= 0x001F) {
						if (yych <= '\n') {
							if (yych <= 0x0008) goto yy18;
							if (yych <= '\t') goto yy16;
							goto yy5;
						} else {
							if (yych == '\r') goto yy15;
						}
					} else {
						if (yych <= 0x0085) {
							if (yych <= ' ') goto yy16;
							if (yych >= 0x0085) goto yy16;
						} else {
							if (yych == 0x00A0) goto yy16;
							if (yych >= 0x1680) goto yy16;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy16;
						} else {
							if (yych <= 0x200A) goto yy16;
							if (yych >= 0x2028) goto yy16;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy16;
						} else {
							if (yych <= 0x205F) goto yy16;
							if (yych == 0x3000) goto yy16;
						}
					}
				}
yy18:
				pos = YYMARKER;
				if (yyaccept <= 0) {
					goto yy3;
				} else {
					goto yy23;
				}
yy19:
				++pos;
				yych = *pos;
yy20:
				if (yych == '\n') goto yy24;
				if (yych != '\r') goto yy19;
yy21:
				yyaccept = 1;
				YYMARKER = ++pos;
				yych = *pos;
				if (yych == '\n') goto yy24;
				if (yych == '\r') goto yy21;
				goto yy19;
yy23:
				{ return TT(TOKEN_COMMENT_LINE,st,pos); }
yy24:
				++pos;
				yych = *pos;
				goto yy23;
// *********************************** [PROTOCOL]
yyc_PROTOCOL:
				yych = *pos;
				if (yych <= '-') {
					if (yych != '\n') goto yy30;
				} else {
					if (yych == '`') goto yy30;
					if (yych <= 'z') goto yy28;
					goto yy30;
				}
yy28:
				++pos;
				yych = *pos;
				goto yy33;
yy29:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_PROTOCOL_METHOD,st,pos); }
yy30:
				++pos;
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy32:
				++pos;
				yych = *pos;
yy33:
				if (yych <= '-') goto yy29;
				if (yych == '`') goto yy29;
				if (yych <= 'z') goto yy32;
				goto yy29;
// *********************************** [SECTION]
yyc_SECTION:
				yych = *pos;
				if (yych <= '-') {
					if (yych != '\n') goto yy39;
				} else {
					if (yych == '`') goto yy39;
					if (yych <= 'z') goto yy37;
					goto yy39;
				}
yy37:
				++pos;
				yych = *pos;
				goto yy42;
yy38:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_SECTION_NAME,st,pos); }
yy39:
				++pos;
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy41:
				++pos;
				yych = *pos;
yy42:
				if (yych <= '-') goto yy38;
				if (yych == '`') goto yy38;
				if (yych <= 'z') goto yy41;
				goto yy38;
// *********************************** [SKIP]
yyc_SKIP:
yy44:
				yych = *pos;
				if (yych == '\n') goto yy46;
				if (yych != '\r') goto yy44;
yy46:
				SetCondition(SCAN_CONDITION_HEAD);
				{ return TT(TOKEN_LEXER_SKIP,st,pos); }
// *********************************** [SPLIT]
yyc_SPLIT:
				yych = *pos;
				if (yych <= 0x1680) {
					if (yych <= '9') {
						if (yych <= '\n') {
							if (yych <= 0x0008) goto yy54;
							if (yych <= '\t') goto yy50;
						} else {
							if (yych == ' ') goto yy50;
							goto yy54;
						}
					} else {
						if (yych <= 0x0085) {
							if (yych <= ':') goto yy52;
							if (yych <= 0x0084) goto yy54;
							goto yy50;
						} else {
							if (yych == 0x00A0) goto yy50;
							if (yych <= 0x167F) goto yy54;
							goto yy50;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy50;
							goto yy54;
						} else {
							if (yych <= 0x200A) goto yy50;
							if (yych <= 0x2027) goto yy54;
							goto yy50;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy50;
							goto yy54;
						} else {
							if (yych <= 0x205F) goto yy50;
							if (yych == 0x3000) goto yy50;
							goto yy54;
						}
					}
				}
yy49:
				pos = YYMARKER;
				goto yy51;
yy50:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				if (yych <= 0x1680) {
					if (yych <= ':') {
						if (yych <= 0x001F) {
							if (yych == '\t') goto yy57;
						} else {
							if (yych <= ' ') goto yy57;
							if (yych >= ':') goto yy55;
						}
					} else {
						if (yych <= 0x009F) {
							if (yych == 0x0085) goto yy57;
						} else {
							if (yych <= 0x00A0) goto yy57;
							if (yych >= 0x1680) goto yy57;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy57;
						} else {
							if (yych <= 0x200A) goto yy57;
							if (yych >= 0x2028) goto yy57;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy57;
						} else {
							if (yych <= 0x205F) goto yy57;
							if (yych == 0x3000) goto yy57;
						}
					}
				}
yy51:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy52:
				++pos;
				yych = *pos;
				goto yy56;
yy53:
				SetCondition(SCAN_CONDITION_VALUE);
				{ return TT(TOKEN_ITEM_SPLIT,st,pos); }
yy54:
				yych = *++pos;
				goto yy51;
yy55:
				++pos;
				yych = *pos;
yy56:
				if (yych <= 0x180D) {
					if (yych <= 0x0084) {
						if (yych <= '\t') {
							if (yych <= 0x0008) goto yy53;
							goto yy55;
						} else {
							if (yych == ' ') goto yy55;
							goto yy53;
						}
					} else {
						if (yych <= 0x00A0) {
							if (yych <= 0x0085) goto yy55;
							if (yych <= 0x009F) goto yy53;
							goto yy55;
						} else {
							if (yych == 0x1680) goto yy55;
							goto yy53;
						}
					}
				} else {
					if (yych <= 0x202E) {
						if (yych <= 0x200A) {
							if (yych <= 0x180E) goto yy55;
							if (yych <= 0x1FFF) goto yy53;
							goto yy55;
						} else {
							if (yych <= 0x2027) goto yy53;
							if (yych <= 0x2029) goto yy55;
							goto yy53;
						}
					} else {
						if (yych <= 0x205F) {
							if (yych <= 0x202F) goto yy55;
							if (yych <= 0x205E) goto yy53;
							goto yy55;
						} else {
							if (yych == 0x3000) goto yy55;
							goto yy53;
						}
					}
				}
yy57:
				++pos;
				yych = *pos;
				if (yych <= 0x1680) {
					if (yych <= ':') {
						if (yych <= 0x001F) {
							if (yych == '\t') goto yy57;
							goto yy49;
						} else {
							if (yych <= ' ') goto yy57;
							if (yych <= '9') goto yy49;
							goto yy55;
						}
					} else {
						if (yych <= 0x009F) {
							if (yych == 0x0085) goto yy57;
							goto yy49;
						} else {
							if (yych <= 0x00A0) goto yy57;
							if (yych <= 0x167F) goto yy49;
							goto yy57;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy57;
							goto yy49;
						} else {
							if (yych <= 0x200A) goto yy57;
							if (yych <= 0x2027) goto yy49;
							goto yy57;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy57;
							goto yy49;
						} else {
							if (yych <= 0x205F) goto yy57;
							if (yych == 0x3000) goto yy57;
							goto yy49;
						}
					}
				}
// *********************************** [START]
yyc_START:
				yych = *pos;
				if (yych <= 0x0085) {
					if (yych <= '"') {
						if (yych <= '\f') {
							if (yych <= 0x0008) goto yy70;
							if (yych <= '\t') goto yy63;
							if (yych <= '\n') goto yy64;
							goto yy70;
						} else {
							if (yych <= '\r') goto yy66;
							if (yych == ' ') goto yy63;
							goto yy70;
						}
					} else {
						if (yych <= '[') {
							if (yych <= '#') goto yy61;
							if (yych <= '-') goto yy70;
							if (yych <= 'Z') goto yy69;
							goto yy67;
						} else {
							if (yych <= '`') {
								if (yych <= '_') goto yy69;
								goto yy70;
							} else {
								if (yych <= 'z') goto yy69;
								if (yych <= 0x0084) goto yy70;
								goto yy63;
							}
						}
					}
				} else {
					if (yych <= 0x200A) {
						if (yych <= 0x1680) {
							if (yych == 0x00A0) goto yy63;
							if (yych <= 0x167F) goto yy70;
							goto yy63;
						} else {
							if (yych == 0x180E) goto yy63;
							if (yych <= 0x1FFF) goto yy70;
							goto yy63;
						}
					} else {
						if (yych <= 0x202F) {
							if (yych <= 0x2027) goto yy70;
							if (yych <= 0x2029) goto yy63;
							if (yych <= 0x202E) goto yy70;
							goto yy63;
						} else {
							if (yych <= 0x205F) {
								if (yych <= 0x205E) goto yy70;
								goto yy63;
							} else {
								if (yych == 0x3000) goto yy63;
								goto yy70;
							}
						}
					}
				}
yy61:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				goto yy88;
yy62:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy63:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				if (yych <= 0x1680) {
					if (yych <= ' ') {
						if (yych <= '\f') {
							if (yych <= 0x0008) goto yy62;
							if (yych <= '\n') goto yy86;
							goto yy62;
						} else {
							if (yych <= '\r') goto yy86;
							if (yych <= 0x001F) goto yy62;
							goto yy86;
						}
					} else {
						if (yych <= 0x009F) {
							if (yych == 0x0085) goto yy86;
							goto yy62;
						} else {
							if (yych <= 0x00A0) goto yy86;
							if (yych <= 0x167F) goto yy62;
							goto yy86;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy86;
							goto yy62;
						} else {
							if (yych <= 0x200A) goto yy86;
							if (yych <= 0x2027) goto yy62;
							goto yy86;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy86;
							goto yy62;
						} else {
							if (yych <= 0x205F) goto yy86;
							if (yych == 0x3000) goto yy86;
							goto yy62;
						}
					}
				}
yy64:
				++pos;
yy65:
				{ return TT(TOKEN_COMMENT_LINE,st,pos); }
yy66:
				yych = *++pos;
				if (yych == '\n') goto yy64;
				goto yy65;
yy67:
				yyaccept = 1;
				yych = *(YYMARKER = ++pos);
				if (yych <= '-') goto yy68;
				if (yych == '`') goto yy68;
				if (yych <= 'z') goto yy72;
yy68:
				SetCondition(SCAN_CONDITION_SECTION);
				{ return TT(TOKEN_SECTION_HEADER,st,pos); }
yy69:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				if (yych <= '-') goto yy62;
				if (yych == '`') goto yy62;
				if (yych <= 'z') goto yy72;
				goto yy62;
yy70:
				yych = *++pos;
				goto yy62;
yy71:
				++pos;
				yych = *pos;
yy72:
				if (yych <= '/') {
					if (yych <= '-') goto yy73;
					if (yych <= '.') goto yy71;
					goto yy74;
				} else {
					if (yych == '`') goto yy73;
					if (yych <= 'z') goto yy71;
				}
yy73:
				pos = YYMARKER;
				if (yyaccept <= 1) {
					if (yyaccept <= 0) {
						goto yy62;
					} else {
						goto yy68;
					}
				} else {
					if (yyaccept <= 2) {
						goto yy81;
					} else {
						goto yy91;
					}
				}
yy74:
				++pos;
				yych = *pos;
				if (yych <= '9') {
					if (yych <= '-') goto yy73;
					if (yych <= '.') goto yy71;
					if (yych <= '/') goto yy74;
				} else {
					if (yych == '`') goto yy73;
					if (yych <= 'z') goto yy71;
					goto yy73;
				}
yy76:
				++pos;
				yych = *pos;
				if (yych <= '9') {
					if (yych <= '-') goto yy73;
					if (yych <= '.') goto yy78;
					if (yych <= '/') goto yy74;
					goto yy76;
				} else {
					if (yych == '`') goto yy73;
					if (yych <= 'z') goto yy71;
					goto yy73;
				}
yy78:
				++pos;
				yych = *pos;
				if (yych <= '9') {
					if (yych <= '-') goto yy73;
					if (yych <= '.') goto yy71;
					if (yych <= '/') goto yy74;
				} else {
					if (yych == '`') goto yy73;
					if (yych <= 'z') goto yy71;
					goto yy73;
				}
yy79:
				yyaccept = 2;
				YYMARKER = ++pos;
				yych = *pos;
				if (yych <= 0x00A0) {
					if (yych <= '/') {
						if (yych <= 0x001F) {
							if (yych == '\t') goto yy82;
						} else {
							if (yych <= ' ') goto yy82;
							if (yych <= '-') goto yy81;
							if (yych <= '.') goto yy71;
							goto yy74;
						}
					} else {
						if (yych <= 'z') {
							if (yych <= '9') goto yy79;
							if (yych != '`') goto yy71;
						} else {
							if (yych == 0x0085) goto yy82;
							if (yych >= 0x00A0) goto yy82;
						}
					}
				} else {
					if (yych <= 0x2027) {
						if (yych <= 0x180D) {
							if (yych == 0x1680) goto yy82;
						} else {
							if (yych <= 0x180E) goto yy82;
							if (yych <= 0x1FFF) goto yy81;
							if (yych <= 0x200A) goto yy82;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych <= 0x2029) goto yy82;
							if (yych == 0x202F) goto yy82;
						} else {
							if (yych <= 0x205F) goto yy82;
							if (yych == 0x3000) goto yy82;
						}
					}
				}
yy81:
				SetCondition(SCAN_CONDITION_PROTOCOL);
				{ return TT(TOKEN_PROTOCOL_NAME,st,pos); }
yy82:
				++pos;
				yych = *pos;
				if (yych <= 0x180D) {
					if (yych <= 0x0084) {
						if (yych <= '\t') {
							if (yych <= 0x0008) goto yy81;
							goto yy82;
						} else {
							if (yych == ' ') goto yy82;
							goto yy81;
						}
					} else {
						if (yych <= 0x00A0) {
							if (yych <= 0x0085) goto yy82;
							if (yych <= 0x009F) goto yy81;
							goto yy82;
						} else {
							if (yych == 0x1680) goto yy82;
							goto yy81;
						}
					}
				} else {
					if (yych <= 0x202E) {
						if (yych <= 0x200A) {
							if (yych <= 0x180E) goto yy82;
							if (yych <= 0x1FFF) goto yy81;
							goto yy82;
						} else {
							if (yych <= 0x2027) goto yy81;
							if (yych <= 0x2029) goto yy82;
							goto yy81;
						}
					} else {
						if (yych <= 0x205F) {
							if (yych <= 0x202F) goto yy82;
							if (yych <= 0x205E) goto yy81;
							goto yy82;
						} else {
							if (yych == 0x3000) goto yy82;
							goto yy81;
						}
					}
				}
yy84:
				yych = *++pos;
				if (yych == '\n') goto yy64;
				goto yy65;
yy85:
				++pos;
				yych = *pos;
yy86:
				if (yych <= 0x1680) {
					if (yych <= 0x001F) {
						if (yych <= '\n') {
							if (yych <= 0x0008) goto yy73;
							if (yych <= '\t') goto yy85;
							goto yy64;
						} else {
							if (yych == '\r') goto yy84;
							goto yy73;
						}
					} else {
						if (yych <= 0x0085) {
							if (yych <= ' ') goto yy85;
							if (yych <= 0x0084) goto yy73;
							goto yy85;
						} else {
							if (yych == 0x00A0) goto yy85;
							if (yych <= 0x167F) goto yy73;
							goto yy85;
						}
					}
				} else {
					if (yych <= 0x2029) {
						if (yych <= 0x1FFF) {
							if (yych == 0x180E) goto yy85;
							goto yy73;
						} else {
							if (yych <= 0x200A) goto yy85;
							if (yych <= 0x2027) goto yy73;
							goto yy85;
						}
					} else {
						if (yych <= 0x205E) {
							if (yych == 0x202F) goto yy85;
							goto yy73;
						} else {
							if (yych <= 0x205F) goto yy85;
							if (yych == 0x3000) goto yy85;
							goto yy73;
						}
					}
				}
yy87:
				++pos;
				yych = *pos;
yy88:
				if (yych == '\n') goto yy92;
				if (yych != '\r') goto yy87;
yy89:
				yyaccept = 3;
				YYMARKER = ++pos;
				yych = *pos;
				if (yych == '\n') goto yy92;
				if (yych == '\r') goto yy89;
				goto yy87;
yy91:
				{ return TT(TOKEN_COMMENT_LINE,st,pos); }
yy92:
				++pos;
				yych = *pos;
				goto yy91;
// *********************************** [VALUE]
yyc_VALUE:
				yych = *pos;
				if (yych <= '!') {
					if (yych != '\n') goto yy99;
				} else {
					if (yych <= '"') goto yy98;
					if (yych == '-') goto yy96;
					goto yy99;
				}
				pos = YYMARKER;
				if (yyaccept <= 1) {
					if (yyaccept <= 0) {
						goto yy97;
					} else {
						goto yy103;
					}
				} else {
					goto yy108;
				}
yy96:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				goto yy105;
yy97:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_LEXER_ERROR,st,pos); }
yy98:
				yyaccept = 0;
				yych = *(YYMARKER = ++pos);
				goto yy101;
yy99:
				yych = *++pos;
				goto yy97;
yy100:
				++pos;
				yych = *pos;
yy101:
				if (yych != '"') goto yy100;
				yyaccept = 1;
				YYMARKER = ++pos;
				yych = *pos;
				if (yych == '"') goto yy100;
yy103:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_ITEM_VALUE_QUOT,st,pos); }
yy104:
				++pos;
				yych = *pos;
yy105:
				if (yych == '\n') goto yy109;
				if (yych != '\r') goto yy104;
yy106:
				yyaccept = 2;
				YYMARKER = ++pos;
				yych = *pos;
				if (yych == '\n') goto yy109;
				if (yych == '\r') goto yy106;
				goto yy104;
yy108:
				SetCondition(SCAN_CONDITION_SKIP);
				{ return TT(TOKEN_ITEM_VALUE,st,pos); }
yy109:
				++pos;
				yych = *pos;
				goto yy108;
			}

	}

};
